### ISSUE TITLE
Option to deploy Spegel and/or provide extra talos config patches

### ISSUE THREAD

**Issue by galexrt** [hcloud-talos/terraform-hcloud-talos#194]
I'm currently looking to deploy Spegel to a cluster created via terraform-hcloud-talos.

For this I need to change the machine config:

```yaml
machine:
  files:
    - path: /etc/cri/conf.d/20-customization.part
      op: create
      content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
```

As far as I know I can patch the machine config after cluster creation using `talosctl` but would it be possible to potentially add a option/toggle to automatically install Spegel or to provide a list of extra config patches?
