### ISSUE TITLE
Hetzner Load Balancer

### ISSUE THREAD

**Issue by jricardooliveira** [hcloud-talos/terraform-hcloud-talos#8]
As talked by email, Is it possible to add option to use hetzner load balancers?

->  to add load-balancer.hetzner.cloud/disable-private-ingress: "true"

Thaks 
Joao

**Comment by mrclrchtr** [comment]
As I wrote in the mail, have you red the following docs?

https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/load_balancers.md

I think you have to add the annotation.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: example-service
  annotations:
    load-balancer.hetzner.cloud/location: hel1
spec:
  selector:
    app: example
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
```

How does your service config look?

**Comment by jricardooliveira** [comment]
Hi Marcel,

Thanks a lot for your help. I've managed to make it work... as I'm not a kubernetes experience professional I struggled a lot... but finally made it.

Take a look how I've done it:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp
  annotations:
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/disable-private-ingress: "true"
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
```

without the use-private-ip the Loadbalancer couldn't get into the container... .and without disable-private-ingress the load balance isn't created.

Thanks,
Joao
